Update billing.md
refractionPOINT/lce_doc pull request #136
Opened 2022-01-28 20:28 UTC by rosshaleliuk

I'd appreciate some help in styling the image as I couldn't make it work. Data source: https://docs.google.com/document/d/1HrSIlTyYSsVO-7nDnmWz7Xu02cZZHS7A6kusAb7dDHQ/edit?usp=sharing

## Description of the change

Billing changes associated with vSensor

2022-01-28 22:03 UTC, maximelb requested changes

2022-01-28 22:03 UTC, maximelb commented on docs/billing.md
> +![image](https://user-images.githubusercontent.com/90273720/151613250-7e158766-0344-4bd2-b91f-5eba8965e22c.png)
Markdown allows for tables, this feels like a better alternative to image: https://github.github.com/gfm/#table

2022-01-28 22:52 UTC, rosshaleliuk commented on docs/billing.md
> +![image](https://user-images.githubusercontent.com/90273720/151613250-7e158766-0344-4bd2-b91f-5eba8965e22c.png)
Thanks @maximelb , admittedly I don't know how to do this without wasting too much time so some help would be highly appreciated :)

2022-01-28 22:53 UTC, rosshaleliuk commented on docs/billing.md
> +![image](https://user-images.githubusercontent.com/90273720/151613250-7e158766-0344-4bd2-b91f-5eba8965e22c.png)
I've never done a proper PR that is not about editing docs...

2022-01-29 01:38 UTC, maximelb approved these changes

2022-01-29 01:48 UTC, merged